//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConditionMatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConditionMatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;conditions&quot; : [ {
        ///    &quot;conditionName&quot; : &quot;Achilles tendinopathy and bursitis&quot;,
        ///    &quot;rhRegisterId&quot; : &quot;F2015L01336&quot;,
        ///    &quot;bopRegisterId&quot; : &quot;F2015L01337&quot;,
        ///    &quot;icdCodes&quot; : [ {
        ///      &quot;version&quot; : &quot;ICD-10-AM&quot;,
        ///      &quot;code&quot; : &quot;M76.6&quot;
        ///    } ]
        ///  }, {
        ///    &quot;conditionName&quot; : &quot;Alzheimer disease&quot;,
        ///    &quot;rhRegisterId&quot; : &quot;F2019L00240&quot;,
        ///    &quot;bopRegisterId&quot; : &quot;F2019L00239&quot;,
        ///    &quot;icdCodes&quot; : [ {
        ///      &quot;version&quot; : &quot;ICD-10-AM&quot;,
        ///      &quot;code&quot; : &quot;G30.0&quot;
        ///    }, {
        ///      &quot;version&quot; : &quot;ICD-10-AM&quot;,
        ///      &quot;code&quot; : &quot;G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string conditionsJson {
            get {
                return ResourceManager.GetString("conditionsJson", resourceCulture);
            }
        }
    }
}
